// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CME_diagram_VerticalData_BODY

/************************************************************
 VerticalData class body
 ************************************************************/

// include associated header file
#include "VerticalData.hpp"

void VerticalData::storeHeight(Height *ht)
{
	if(heights.empty())
	{
		this->heights.push(*ht);
	}
	else
	{
		this->heights.push(*ht);
		this->calculateVelocity();
		this->heights.pop();
	}
}

/**
 *
 */
float VerticalData::getVelocity() {
	return this->velocity;
}


void VerticalData::calculateVelocity() {
	float deltaT = 0;
	float deltaH = 0;
	time_t currentTime = this->heights.back().getTime();
	time_t previousTime = this->heights.front().getTime();
	float currentHeight = this->heights.back().getData();
	float previousHeight = this->heights.front().getData();

	deltaT = currentTime - previousTime;
	deltaH = currentHeight - previousHeight;

	this->velocity = (deltaH/deltaT);
}

/************************************************************
 End of VerticalData class body
 ************************************************************/

