// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CME_DIAGRAM_VERTICALDATA_H
#define CME_DIAGRAM_VERTICALDATA_H

/************************************************************
 VerticalData class header
 ************************************************************/

//#include "CME_diagram/Pkg_CME_diagram.h"

//#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include <cstdlib>
#include <iostream>
#include <ctime>

#include "../includes/Height.hpp"

using namespace std;
/************************************************************/
/**
 * 
 */
class VerticalData {
public:

	/**
	 * Create an empty vertical Data Object
	 *
	 */
	VerticalData();

	/**
	 * 
	 * @param height 
	 */
	VerticalData(Height /*in*/previous);

	/**
	 * 
	 * @param height 
	 */
	void setCurrentHeight(float /*in*/height);

	/**
	 * 
	 * @return  
	 */
	float getCurrentHeight();

	/**
	 * 
	 * @return time 
	 */
	time_t getCurrentTime();

	/**
	 * 
	 */
	float getVelocity();

	/**
	 * 
	 */
	~VerticalData(void);

private:
	/**
	 * 
	 */
	float currentHeight;
	/**
	 * 
	 */
	float previousHeight;
	/**
	 * 
	 */
	time_t currentTime;
	/**
	 * 
	 */
	time_t previousTime;
	/**
	 * 
	 */
	float velocity;

	/**
	 * 
	 * @param height 
	 */
	void setPreviousHeight(Height /*in*/prevHeight);

	/**
	 * 
	 * @return height 
	 */
	float getPreviouseHeight();

	/**
	 * 
	 * @param time 
	 */
	void setCurrentTime(time_t /*in*/time);

	/**
	 * 
	 */
	time_t getPreviouseTime();

	/**
	 * 
	 * @param time 
	 */
	void setPreviousTime(time_t /*in*/time);

	/**
	 * 
	 */
	void calculateVelocity();
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of VerticalData class header
 ************************************************************/

#endif
