// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CME_DIAGRAM_VERTICALDATA_H
#define CME_DIAGRAM_VERTICALDATA_H

/************************************************************
 VerticalData class header
 ************************************************************/

//#include "CME_diagram/Pkg_CME_diagram.h"

//#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include <cstdlib>
#include <queue>
#include <ctime>
#include "../includes/Height.hpp"

using namespace std;
/************************************************************/
/**
 * 
 */
class VerticalData {
public:

	/*
	 * Store height object
	 * @param[in] currentHeight
	 */
	void storeHeight(Height *ht);

	/*
	 * @return vertical velocity
	 */
	float getVelocity();


private:
	queue <Height> heights;

	float velocity;


	void calculateVelocity();
};

/************************************************************
 End of VerticalData class header
 ************************************************************/

#endif
